package cloud.entity.classroom.every;

public class Filetype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FileType.id
     *
     * @mbg.generated Thu Jun 22 16:03:44 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column FileType.name
     *
     * @mbg.generated Thu Jun 22 16:03:44 CST 2017
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FileType.id
     *
     * @return the value of FileType.id
     *
     * @mbg.generated Thu Jun 22 16:03:44 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FileType.id
     *
     * @param id the value for FileType.id
     *
     * @mbg.generated Thu Jun 22 16:03:44 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column FileType.name
     *
     * @return the value of FileType.name
     *
     * @mbg.generated Thu Jun 22 16:03:44 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column FileType.name
     *
     * @param name the value for FileType.name
     *
     * @mbg.generated Thu Jun 22 16:03:44 CST 2017
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}